# Generated by Django 4.1.5 on 2023-01-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prodects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodect_image', models.ImageField(upload_to='prodect')),
                ('prodect_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prodect_right', models.CharField(blank=True, max_length=100, null=True)),
                ('prodect_offerright', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
